name: Deploy the Keyboard Trainer

on:
  push:
    branches:
      - main
    paths:
      - 'keyboard-trainer/**/*.*'
  workflow_dispatch:


jobs:
  deploy-html:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./keyboard-trainer
          destination_dir: keyboard-trainer
          keep_files: true