name: Build LaTeX PDFs

on:
  push:
    paths:
      - 'stories/**/*.tex'
  workflow_dispatch:

jobs:
  build-pdfs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install XeLaTeX and fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          texlive-xetex \
          texlive-lang-arabic \
          texlive-fonts-recommended \
          texlive-latex-extra \
          fonts-sil-charis
          fonts-david-clm

    - name: Compile all PDFs
      run: |
        rm -rf output
        mkdir -p output
        for texfile in $(find stories -name "*.tex"); do
          echo "Compiling $texfile..."
          subdir=$(dirname "$texfile")
          tmpdir=$(mktemp -d)
          xelatex -output-directory="$tmpdir" "$texfile"
          mkdir -p "output/$subdir"
          # Copy only the PDF to output preserving folder structure
          cp "$tmpdir/$(basename "${texfile%.tex}.pdf")" "output/$subdir/"
          rm -rf "$tmpdir"
        done

    - name: Deploy to gh-pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages

