name: Build LaTeX PDFs

on:
  push:
    paths:
      - 'stories/**/*.tex'
  workflow_dispatch:

jobs:
  build-pdfs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install XeLaTeX and fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          texlive-xetex \
          texlive-lang-arabic \
          texlive-fonts-recommended \
          texlive-latex-extra \
          fonts-sil-charis

    - name: Compile all PDFs
      run: |
        mkdir -p output
        for texfile in $(find stories -name "*.tex"); do
          echo "Compiling $texfile..."
          subdir=$(dirname "$texfile")
          outdir="output/$subdir"
          mkdir -p "$outdir"
          xelatex -output-directory="$outdir" "$texfile"
        done

    - name: Deploy to gh-pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages

